### ISSUE TITLE
Is this still necessary for bitcore?

### ISSUE THREAD

**Issue by runn1ng** [str4d/zcash#17]
Is this patching still necessary for bitcore support? Or is the address index already built-in in zcash?

And if it's necessary, will it be rebased on new zcash?

**Comment by prusnak** [comment]
Bump

**Comment by slush0** [comment]
Recently there was DoS bug in zcash. We'd need to know which zcash version we should use for insight. Thanks for any information.

**Comment by slush0** [comment]
It seems it is still needed. Zcash does not contain address index yet.

**Comment by daira** [comment]
Yes it's still necessary. Updating the patches to more recent Zcash is https://github.com/zcash/zcash/issues/2382 , so this ticket can be closed.
