### ISSUE TITLE
Please update zcash for bitcore

### ISSUE THREAD

**Issue by slush0** [str4d/zcash#19]
Hello,

bitcore fork stil uses zcash  v1.0.4. Not only it is outdated, buggy and unsupported, but it even cannot build, because you remove dependencies from z.cash site (namely https://z.cash/depends-sources/zeromq-4.0.4.tar.gz).

Please update zcash for bitcore to latest binary, otherwise we'll have to stop supporting zcash in TREZOR :(.

**Comment by radix42** [comment]
I agree that it's bitrotted a bit, and needs some work to be updated to 1.0.8-1...but I just built it last week

**Comment by nathan-at-least** [comment]
Hello. I apologize for the trouble. I had not realized anyone was relying on this fork other than our own internal explorer projects. I've raised the priority of this, but unfortunately it's too late for 1.0.9 (due out early next week).

Please see the upstream Zcash ticket, and comment there to ensure more of the zcash-dev team notices it: https://github.com/zcash/zcash/issues/1534#issuecomment-300859932

**Comment by nathan-at-least** [comment]
Note, Trezor and @radix42 are relying on this branch: https://github.com/str4d/zcash/tree/v1.0.4-bitcore-3

**Comment by daira** [comment]
Moved to https://github.com/zcash/zcash/issues/1534 ; should be closed here.
