### ISSUE TITLE
Block version 04000000 gets rejected

### ISSUE THREAD

**Issue by razakal** [str4d/zcash#2]
Block version 04000000 gets rejected in the mining.notify notification.

Miner gives:
> [WARN] Invalid or unsupported block header version.

Block version 00000004 gets accepted.
This might be an endianness problem.

**Comment by ocminer** [comment]
Confirmed

**Comment by str4d** [comment]
Fixed by 875f1b32d114bdef80259d5439d44c79ad3acdd0
