### ISSUE TITLE
mining.submit sends invalid json

### ISSUE THREAD

**Issue by razakal** [str4d/zcash#3]
mining.submit is sending invalid json messages.
There is one quote too many after the solution.

example:

> {"id": 4, "method": "mining.submit", "params": ["x",""9295","e3c7e757","00000000000000000000000000000000","0040865486878a6848bb6046376fe4b435da3e081d08ee7d88f012939f54a928b92d77e92fae149fa47306abc617925c2f1f4ffb7228a1c549e0bd701f12033bf5c5f88893032db6b2943b16f3a84768855b73f500ac8f78b65ce93526ce47e5cfe6b7cf9f555f1ab0010ad9008642abf7d95a3343d1e87851f85f744bc7207b2e7c365673df683287f17e49a0afc929dee31844510e429b6594fb332a19addafcf13a6bb77fc00b01a5d5f1fc61af4183c9a15738d71210652a9343a818f952bb64924a1afea392a1d9e40761451b51bcd51a5e831460677979576771f7f1b388768d5cfd11f6223ff1c762208ce5a26c26868e5c2c29c3e71dd3e009c0292ac8033717e5a89680786ecb76ca4a5d0004361f6bf2af4e2f6f592d174a2fbdf6e27f16d934912ac6dcaeccb2bb0fcd7c56636eb4bfb2bc26fbfa6e5ebdf777d1ac4d91eaf308462f426177269eba72fa03bae6f50b5520eae4ce87c9b0c1882a49bcfad9040638d0a1c92e8c3ba559f18503e284996eeeae967f094d120ba90a4c397937e20178469ecc9b314aed282ecf33cbcaa8778dc8f4d33535a467371bfa7a74ea04393e3554faa4bff5bb04d39abe4f693990dc0ef90f7d763d904d5446c9f576c9b03c7f929651362be605ffb508fd0675254aa0f52b24a9e771a1fc5a6ba212cc2099e39adad1b184043268d20a8daa121f9c09076330fd4d2b469fea6c82aab93c61e215663d13941a84a6adae4d106eed51b52d32f525ad78ca1aa69e409ca6108522792dd0fd97ac0f6825360285b69dd856212db3ebf7b65becf186f442c1016f5772dd89330e36042134c4abbabccf72b340e9eba5450c0f3678297c0bc6871624caf953229b5254eff1e0a63c749914e7627695cc1edf0a7cb242e4a14dfa4dd4b673e9311a2676ca14584fed1f93948e1fc58d9786bae175009dd92a11a630c76e7f94d118466dbbbc18df1bbc107c579599921067a2b1c1985efc280126fc71b68f1cbd527e422b3aa3aaaec85f4446a2ca39cedb7ebc74760c43d0baa7ade06207d0d4f0e1127a4138f7b3029066ae9075fb3bb0f9c35686b86a29d1ce732b9404caddb09c01f8e421c8564f8254fe7a651c7a4563154b2952f1c988ff051832504eb99f926d0b363528348b8eec7e5433efa407c90162df684b07f59ac60605c8d79db347a5d6d4be77c45ae57e420868f5a730232e4e7326a8a01da43d03ccb33817f1e85aaf80d10806174b40e14929378b94cb2a268ac5c7f23a4fdd1e3ccf061591e16fbc33e694245d9592562e9dfff50cb7c964f485bfeadf36f3ca5aa99a6d51a4f8f2153cbbaf1d23663731f7c7e3dc78e2166676b758537a0ddaeaad7c36345bd011a387274b6bda2c95f49e6c2ee24ff24190462a9037c4c2a12d4d72ec12bf45ee02daf08cfa9fc4bfb012905ee15a0125865050e33564d0d67332369f89d7d7574b85f152ba57483a1880209e7b9cb7179193ead5a49f10ed2d425f999cd01432c7575f2fe2a5278ddef3754e9ecec538a998007709903cbae006a089a393f61b43772379c5cd17cbf61ad9762142d2a807c6f3b401b9ac15c320fd59f3f810033335215ea0370c54337d1cc628c263ddd7f4842ba1097dbd6c6905af2263e9ca6a692146c31c0bda03d1f22c70c6cae96d322691c0dc8fe3540eff5aa71be4a5689820050da6f09c1273fd51ab84867c7e901c8cce59e107caba538811e27ceedbf49dcc1779ef2d5a74dba26e214d753614777f484771c032bb8b8f0ac986be3483cb3adc8533151a406d49c16072f6873a2564e229e194ebcb22e5584fdaff198284d4fcd40c8edb4a3014dfa9d151cc2b2fed7d83b3c0fd9e111c54ad42bca4061faa93e2437cd95935b27732bd6c""]}

**Comment by str4d** [comment]
Closed in 2789595735b4bb7923cbcb49b7eb00a3a05fc361
